### ISSUE TITLE
Failed in compiling model

### ISSUE THREAD

**Issue by Ting011** [sophgo/ChatGLM2-TPU#2]
### 运行环境
软件
```
使用了readme中提供的官方sophon docker 镜像
```

硬件
SC7 TPU 算力卡， 由于散热问题目前没有安装到服务器中，仅以此项目作软件模型编译测试

### 问题描述： 
根据 readme 中的 instruction 进行到模型编译一步时:
```
./compile.sh
```

具体命令是：
```
model_transform.py --model_name glm_block_cache_0 --model_def ../glm_block_cache_0.onnx --mlir glm_block_cache_0.mlir
```

出现了Runtime Error, 如下
```
RuntimeError: [!Error]: tpuc-opt glm_block_cache_0_origin.mlir --shape-infer --canonicalize --extra-optimize -o glm_block_cache_0.mlir
```

### 部分报错日志:
此日志前的运行log均无报错
```
+ model_transform.py --model_name glm_block_cache_0 --model_def ../glm_block_cache_0.onnx --mlir glm_block_cache_0.mlir
SOPHGO Toolchain v1.2.beta.0-94-g42841474-20230720
2023/07/20 15:29:02 - INFO : 
         _____________________________________________________ 
        | preprocess:                                           |
        |   (x - mean) * scale                                  |
        '-------------------------------------------------------'
  config Preprocess args : 
        resize_dims           : same to net input dims
        keep_aspect_ratio     : False
        keep_ratio_mode       : letterbox
        pad_value             : 0
        pad_type              : center
        --------------------------
        mean                  : [0.0, 0.0, 0.0]
        scale                 : [1.0, 1.0, 1.0]
        --------------------------
        pixel_format          : bgr
        channel_format        : nchw

--------------------------------
Before assigning input_shape:
True
True
Run onnxsim 1 times, model simplified: True
--------------------------------
After assigning input_shape:
True
True
Run onnxsim 1 times, model simplified: True
--------------------------------
Save mlir file: glm_block_cache_0_origin.mlir
[Running]: tpuc-opt glm_block_cache_0_origin.mlir --shape-infer --canonicalize --extra-optimize -o glm_block_cache_0.mlir 
tpuc-opt: ../lib/Dialect/Top/Interfaces/Reshape.cpp:90: void tpu_mlir::top::ReshapeOp::shape_inference(): Assertion `num_input == num_output' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: tpuc-opt glm_block_cache_0_origin.mlir --init --shape-infer --canonicalize --extra-optimize --deinit --mlir-print-debuginfo -o glm_block_cache_0.mlir
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  tpuc-opt        0x000056375cb510aa
1  tpuc-opt        0x000056375cb4e3ac
2  libpthread.so.0 0x00007fda1e47d980
3  libc.so.6       0x00007fda1d54ae87 gsignal + 199
4  libc.so.6       0x00007fda1d54c7f1 abort + 321
5  libc.so.6       0x00007fda1d53c3fa
6  libc.so.6       0x00007fda1d53c472
7  tpuc-opt        0x000056375c7830b6
8  tpuc-opt        0x000056375c7026a7
9  tpuc-opt        0x000056375c7e35b4
10 tpuc-opt        0x000056375bf4709c
11 tpuc-opt        0x000056375c7e57c1
12 tpuc-opt        0x000056375c8b1b5e
13 tpuc-opt        0x000056375c8b2a48
14 tpuc-opt        0x000056375c8b308f
15 tpuc-opt        0x000056375bee31c5
16 tpuc-opt        0x000056375bee3ddb
17 tpuc-opt        0x000056375bee3fc2
18 tpuc-opt        0x000056375cacf4cf
19 tpuc-opt        0x000056375bedcef2
20 tpuc-opt        0x000056375bee4377
21 tpuc-opt        0x000056375bece150
22 libc.so.6       0x00007fda1d52dc87 __libc_start_main + 231
23 tpuc-opt        0x000056375beda5ea
Aborted (core dumped)
Traceback (most recent call last):
  File "/workspace/tpu-mlir/python/tools/model_transform.py", line 261, in <module>
    tool.model_transform(args.mlir, args.add_postprocess)
  File "/workspace/tpu-mlir/python/tools/model_transform.py", line 51, in model_transform
    mlir_opt_for_top(mlir_origin, self.mlir_file, add_postprocess)
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 60, in mlir_opt_for_top
    _os_system(cmd)
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 50, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt glm_block_cache_0_origin.mlir --shape-infer --canonicalize --extra-optimize -o glm_block_cache_0.mlir 
```

### 补充描述
LLVM-symbollizer 未安装

**Comment by HarmonyHu** [comment]
你好，可以用最新的tpu-mlir编译后再compile

**Comment by Ting011** [comment]
更新 tpu-mlir 到最新版后问题解决。
补充： 重新创建了容器宾重复操作，sentencepiece 没有使用readme中提到的方法而是直接pip install。
